{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# Load the s&p500 csv file to read the csv names\n",
    "sp500_components = pd.read_csv('sp500.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "\n",
    "# Create a matrix of 4482 by ~504 by 4, I only need 4 columns per stock, per day, for 4482 days of data or 18 years.\n",
    "days = 4482   \n",
    "components = len(sp500_components)\n",
    "columns = 4    # I'm only using High, Low, Open and Close columns \n",
    "\n",
    "prepared_data_matrix = np.zeros((days,components,columns))\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def add_to_data_matrix(csv_file, index):\n",
    "    \n",
    "    csv_data = pd.read_csv(csv_file)\n",
    "    \n",
    "    date = (len(prepared_data_matrix) - 1)\n",
    "    data_size = (len(csv_data) -1)\n",
    "    \n",
    "    if date <= data_size:\n",
    "        counter = date   # 4528 spots counting from the 0th index\n",
    "    else:\n",
    "        counter = data_size # Some number less than 4528\n",
    "    \n",
    "    print('counter =', counter)\n",
    "    \n",
    "    while counter >= 0:\n",
    "        \n",
    "        prepared_data_matrix[date][index][0] = csv_data['Open'][counter]\n",
    "        prepared_data_matrix[date][index][1] = csv_data['High'][counter]\n",
    "        prepared_data_matrix[date][index][2] = csv_data['Low'][counter]\n",
    "        prepared_data_matrix[date][index][3] = csv_data['Close'][counter]\n",
    "        date -= 1\n",
    "        counter -= 1\n",
    "        \n",
    "    print('Finished adding', csv_file, 'data to the prepared_data_matrix!')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 A.csv\n",
      "counter = 4481\n",
      "Finished adding A.csv data to the prepared_data_matrix!\n",
      "1 AAL.csv\n",
      "counter = 3144\n",
      "Finished adding AAL.csv data to the prepared_data_matrix!\n",
      "2 AAP.csv\n",
      "counter = 4107\n",
      "Finished adding AAP.csv data to the prepared_data_matrix!\n",
      "3 AAPL.csv\n",
      "counter = 4481\n",
      "Finished adding AAPL.csv data to the prepared_data_matrix!\n",
      "4 ABBV.csv\n",
      "counter = 1315\n",
      "Finished adding ABBV.csv data to the prepared_data_matrix!\n",
      "5 ABC.csv\n",
      "counter = 4481\n",
      "Finished adding ABC.csv data to the prepared_data_matrix!\n",
      "6 ABMD.csv\n",
      "counter = 4481\n",
      "Finished adding ABMD.csv data to the prepared_data_matrix!\n",
      "7 ABT.csv\n",
      "counter = 4481\n",
      "Finished adding ABT.csv data to the prepared_data_matrix!\n",
      "8 ACN.csv\n",
      "counter = 4196\n",
      "Finished adding ACN.csv data to the prepared_data_matrix!\n",
      "9 ADBE.csv\n",
      "counter = 4481\n",
      "Finished adding ADBE.csv data to the prepared_data_matrix!\n",
      "10 ADI.csv\n",
      "counter = 4481\n",
      "Finished adding ADI.csv data to the prepared_data_matrix!\n",
      "11 ADM.csv\n",
      "counter = 4481\n",
      "Finished adding ADM.csv data to the prepared_data_matrix!\n",
      "12 ADP.csv\n",
      "counter = 4481\n",
      "Finished adding ADP.csv data to the prepared_data_matrix!\n",
      "13 ADS.csv\n",
      "counter = 4219\n",
      "Finished adding ADS.csv data to the prepared_data_matrix!\n",
      "14 ADSK.csv\n",
      "counter = 4481\n",
      "Finished adding ADSK.csv data to the prepared_data_matrix!\n",
      "15 AEE.csv\n",
      "counter = 4481\n",
      "Finished adding AEE.csv data to the prepared_data_matrix!\n",
      "16 AEP.csv\n",
      "counter = 4481\n",
      "Finished adding AEP.csv data to the prepared_data_matrix!\n",
      "17 AES.csv\n",
      "counter = 4481\n",
      "Finished adding AES.csv data to the prepared_data_matrix!\n",
      "18 AET.csv\n",
      "counter = 4481\n",
      "Finished adding AET.csv data to the prepared_data_matrix!\n",
      "19 AFL.csv\n",
      "counter = 4481\n",
      "Finished adding AFL.csv data to the prepared_data_matrix!\n",
      "20 AGN.csv\n",
      "counter = 4481\n",
      "Finished adding AGN.csv data to the prepared_data_matrix!\n",
      "21 AIG.csv\n",
      "counter = 4481\n",
      "Finished adding AIG.csv data to the prepared_data_matrix!\n",
      "22 AIV.csv\n",
      "counter = 4481\n",
      "Finished adding AIV.csv data to the prepared_data_matrix!\n",
      "23 AIZ.csv\n",
      "counter = 3558\n",
      "Finished adding AIZ.csv data to the prepared_data_matrix!\n",
      "24 AJG.csv\n",
      "counter = 4481\n",
      "Finished adding AJG.csv data to the prepared_data_matrix!\n",
      "25 AKAM.csv\n",
      "counter = 4481\n",
      "Finished adding AKAM.csv data to the prepared_data_matrix!\n",
      "26 ALB.csv\n",
      "counter = 4481\n",
      "Finished adding ALB.csv data to the prepared_data_matrix!\n",
      "27 ALGN.csv\n",
      "counter = 4314\n",
      "Finished adding ALGN.csv data to the prepared_data_matrix!\n",
      "28 ALK.csv\n",
      "counter = 4481\n",
      "Finished adding ALK.csv data to the prepared_data_matrix!\n",
      "29 ALL.csv\n",
      "counter = 4481\n",
      "Finished adding ALL.csv data to the prepared_data_matrix!\n",
      "30 ALLE.csv\n",
      "counter = 1094\n",
      "Finished adding ALLE.csv data to the prepared_data_matrix!\n",
      "31 ALXN.csv\n",
      "counter = 4481\n",
      "Finished adding ALXN.csv data to the prepared_data_matrix!\n",
      "32 AMAT.csv\n",
      "counter = 4481\n",
      "Finished adding AMAT.csv data to the prepared_data_matrix!\n",
      "33 AMD.csv\n",
      "counter = 4481\n",
      "Finished adding AMD.csv data to the prepared_data_matrix!\n",
      "34 AME.csv\n",
      "counter = 4481\n",
      "Finished adding AME.csv data to the prepared_data_matrix!\n",
      "35 AMG.csv\n",
      "counter = 4481\n",
      "Finished adding AMG.csv data to the prepared_data_matrix!\n",
      "36 AMGN.csv\n",
      "counter = 4481\n",
      "Finished adding AMGN.csv data to the prepared_data_matrix!\n",
      "37 AMP.csv\n",
      "counter = 3152\n",
      "Finished adding AMP.csv data to the prepared_data_matrix!\n",
      "38 AMT.csv\n",
      "counter = 4481\n",
      "Finished adding AMT.csv data to the prepared_data_matrix!\n",
      "39 AMZN.csv\n",
      "counter = 4481\n",
      "Finished adding AMZN.csv data to the prepared_data_matrix!\n",
      "40 ANDV.csv\n",
      "counter = 161\n",
      "Finished adding ANDV.csv data to the prepared_data_matrix!\n",
      "41 ANSS.csv\n",
      "counter = 4481\n",
      "Finished adding ANSS.csv data to the prepared_data_matrix!\n",
      "42 ANTM.csv\n",
      "counter = 4128\n",
      "Finished adding ANTM.csv data to the prepared_data_matrix!\n",
      "43 AON.csv\n",
      "counter = 4481\n",
      "Finished adding AON.csv data to the prepared_data_matrix!\n",
      "44 AOS.csv\n",
      "counter = 4481\n",
      "Finished adding AOS.csv data to the prepared_data_matrix!\n",
      "45 APA.csv\n",
      "counter = 4481\n",
      "Finished adding APA.csv data to the prepared_data_matrix!\n",
      "46 APC.csv\n",
      "counter = 4481\n",
      "Finished adding APC.csv data to the prepared_data_matrix!\n",
      "47 APD.csv\n",
      "counter = 4481\n",
      "Finished adding APD.csv data to the prepared_data_matrix!\n",
      "48 APH.csv\n",
      "counter = 4481\n",
      "Finished adding APH.csv data to the prepared_data_matrix!\n",
      "49 APTV.csv\n",
      "counter = 73\n",
      "Finished adding APTV.csv data to the prepared_data_matrix!\n",
      "50 ARE.csv\n",
      "counter = 4481\n",
      "Finished adding ARE.csv data to the prepared_data_matrix!\n",
      "51 ARNC.csv\n",
      "counter = 4481\n",
      "Finished adding ARNC.csv data to the prepared_data_matrix!\n",
      "52 ATVI.csv\n",
      "counter = 4481\n",
      "Finished adding ATVI.csv data to the prepared_data_matrix!\n",
      "53 AVB.csv\n",
      "counter = 4481\n",
      "Finished adding AVB.csv data to the prepared_data_matrix!\n",
      "54 AVGO.csv\n",
      "counter = 2173\n",
      "Finished adding AVGO.csv data to the prepared_data_matrix!\n",
      "55 AVY.csv\n",
      "counter = 4481\n",
      "Finished adding AVY.csv data to the prepared_data_matrix!\n",
      "56 AWK.csv\n",
      "counter = 2498\n",
      "Finished adding AWK.csv data to the prepared_data_matrix!\n",
      "57 AXP.csv\n",
      "counter = 4481\n",
      "Finished adding AXP.csv data to the prepared_data_matrix!\n",
      "58 AZO.csv\n",
      "counter = 4481\n",
      "Finished adding AZO.csv data to the prepared_data_matrix!\n",
      "59 BA.csv\n",
      "counter = 4481\n",
      "Finished adding BA.csv data to the prepared_data_matrix!\n",
      "60 BAC.csv\n",
      "counter = 4481\n",
      "Finished adding BAC.csv data to the prepared_data_matrix!\n",
      "61 BAX.csv\n",
      "counter = 4481\n",
      "Finished adding BAX.csv data to the prepared_data_matrix!\n",
      "62 BBT.csv\n",
      "counter = 4481\n",
      "Finished adding BBT.csv data to the prepared_data_matrix!\n",
      "63 BBY.csv\n",
      "counter = 4481\n",
      "Finished adding BBY.csv data to the prepared_data_matrix!\n",
      "64 BDX.csv\n",
      "counter = 4481\n",
      "Finished adding BDX.csv data to the prepared_data_matrix!\n",
      "65 BEN.csv\n",
      "counter = 4481\n",
      "Finished adding BEN.csv data to the prepared_data_matrix!\n",
      "File not found!\n",
      "67 BHF.csv\n",
      "counter = 158\n",
      "Finished adding BHF.csv data to the prepared_data_matrix!\n",
      "68 BHGE.csv\n",
      "counter = 180\n",
      "Finished adding BHGE.csv data to the prepared_data_matrix!\n",
      "69 BIIB.csv\n",
      "counter = 4481\n",
      "Finished adding BIIB.csv data to the prepared_data_matrix!\n",
      "70 BK.csv\n",
      "counter = 4481\n",
      "Finished adding BK.csv data to the prepared_data_matrix!\n",
      "71 BKNG.csv\n",
      "counter = 13\n",
      "Finished adding BKNG.csv data to the prepared_data_matrix!\n",
      "72 BLK.csv\n",
      "counter = 4481\n",
      "Finished adding BLK.csv data to the prepared_data_matrix!\n",
      "73 BLL.csv\n",
      "counter = 4481\n",
      "Finished adding BLL.csv data to the prepared_data_matrix!\n",
      "74 BMY.csv\n",
      "counter = 4481\n",
      "Finished adding BMY.csv data to the prepared_data_matrix!\n",
      "75 BR.csv\n",
      "counter = 2765\n",
      "Finished adding BR.csv data to the prepared_data_matrix!\n",
      "File not found!\n",
      "77 BSX.csv\n",
      "counter = 4481\n",
      "Finished adding BSX.csv data to the prepared_data_matrix!\n",
      "78 BWA.csv\n",
      "counter = 4481\n",
      "Finished adding BWA.csv data to the prepared_data_matrix!\n",
      "79 BXP.csv\n",
      "counter = 4481\n",
      "Finished adding BXP.csv data to the prepared_data_matrix!\n",
      "80 C.csv\n",
      "counter = 4481\n",
      "Finished adding C.csv data to the prepared_data_matrix!\n",
      "81 CA.csv\n",
      "counter = 4481\n",
      "Finished adding CA.csv data to the prepared_data_matrix!\n",
      "82 CAG.csv\n",
      "counter = 4481\n",
      "Finished adding CAG.csv data to the prepared_data_matrix!\n",
      "83 CAH.csv\n",
      "counter = 4481\n",
      "Finished adding CAH.csv data to the prepared_data_matrix!\n",
      "84 CAT.csv\n",
      "counter = 4481\n",
      "Finished adding CAT.csv data to the prepared_data_matrix!\n",
      "85 CB.csv\n",
      "counter = 4481\n",
      "Finished adding CB.csv data to the prepared_data_matrix!\n",
      "86 CBOE.csv\n",
      "counter = 1958\n",
      "Finished adding CBOE.csv data to the prepared_data_matrix!\n",
      "87 CBRE.csv\n",
      "counter = 3\n",
      "Finished adding CBRE.csv data to the prepared_data_matrix!\n",
      "88 CBS.csv\n",
      "counter = 3096\n",
      "Finished adding CBS.csv data to the prepared_data_matrix!\n",
      "89 CCI.csv\n",
      "counter = 4481\n",
      "Finished adding CCI.csv data to the prepared_data_matrix!\n",
      "90 CCL.csv\n",
      "counter = 4481\n",
      "Finished adding CCL.csv data to the prepared_data_matrix!\n",
      "91 CDNS.csv\n",
      "counter = 4481\n",
      "Finished adding CDNS.csv data to the prepared_data_matrix!\n",
      "92 CELG.csv\n",
      "counter = 4481\n",
      "Finished adding CELG.csv data to the prepared_data_matrix!\n",
      "93 CERN.csv\n",
      "counter = 4481\n",
      "Finished adding CERN.csv data to the prepared_data_matrix!\n",
      "94 CF.csv\n",
      "counter = 3176\n",
      "Finished adding CF.csv data to the prepared_data_matrix!\n",
      "95 CFG.csv\n",
      "counter = 881\n",
      "Finished adding CFG.csv data to the prepared_data_matrix!\n",
      "96 CHD.csv\n",
      "counter = 4481\n",
      "Finished adding CHD.csv data to the prepared_data_matrix!\n",
      "97 CHRW.csv\n",
      "counter = 4481\n",
      "Finished adding CHRW.csv data to the prepared_data_matrix!\n",
      "98 CHTR.csv\n",
      "counter = 2069\n",
      "Finished adding CHTR.csv data to the prepared_data_matrix!\n",
      "99 CI.csv\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "counter = 4481\n",
      "Finished adding CI.csv data to the prepared_data_matrix!\n",
      "100 CINF.csv\n",
      "counter = 4481\n",
      "Finished adding CINF.csv data to the prepared_data_matrix!\n",
      "101 CL.csv\n",
      "counter = 4481\n",
      "Finished adding CL.csv data to the prepared_data_matrix!\n",
      "102 CLX.csv\n",
      "counter = 4481\n",
      "Finished adding CLX.csv data to the prepared_data_matrix!\n",
      "103 CMA.csv\n",
      "counter = 4481\n",
      "Finished adding CMA.csv data to the prepared_data_matrix!\n",
      "104 CMCSA.csv\n",
      "counter = 4481\n",
      "Finished adding CMCSA.csv data to the prepared_data_matrix!\n",
      "105 CME.csv\n",
      "counter = 3850\n",
      "Finished adding CME.csv data to the prepared_data_matrix!\n",
      "106 CMG.csv\n",
      "counter = 3061\n",
      "Finished adding CMG.csv data to the prepared_data_matrix!\n",
      "107 CMI.csv\n",
      "counter = 4481\n",
      "Finished adding CMI.csv data to the prepared_data_matrix!\n",
      "108 CMS.csv\n",
      "counter = 4481\n",
      "Finished adding CMS.csv data to the prepared_data_matrix!\n",
      "109 CNC.csv\n",
      "counter = 4097\n",
      "Finished adding CNC.csv data to the prepared_data_matrix!\n",
      "110 CNP.csv\n",
      "counter = 4481\n",
      "Finished adding CNP.csv data to the prepared_data_matrix!\n",
      "111 COF.csv\n",
      "counter = 4481\n",
      "Finished adding COF.csv data to the prepared_data_matrix!\n",
      "112 COG.csv\n",
      "counter = 4481\n",
      "Finished adding COG.csv data to the prepared_data_matrix!\n",
      "113 COL.csv\n",
      "counter = 4219\n",
      "Finished adding COL.csv data to the prepared_data_matrix!\n",
      "114 COO.csv\n",
      "counter = 4481\n",
      "Finished adding COO.csv data to the prepared_data_matrix!\n",
      "115 COP.csv\n",
      "counter = 4481\n",
      "Finished adding COP.csv data to the prepared_data_matrix!\n",
      "116 COST.csv\n",
      "counter = 4481\n",
      "Finished adding COST.csv data to the prepared_data_matrix!\n",
      "117 COTY.csv\n",
      "counter = 1204\n",
      "Finished adding COTY.csv data to the prepared_data_matrix!\n",
      "118 CPB.csv\n",
      "counter = 4481\n",
      "Finished adding CPB.csv data to the prepared_data_matrix!\n",
      "119 CRM.csv\n",
      "counter = 3463\n",
      "Finished adding CRM.csv data to the prepared_data_matrix!\n",
      "120 CSCO.csv\n",
      "counter = 4481\n",
      "Finished adding CSCO.csv data to the prepared_data_matrix!\n",
      "121 CSX.csv\n",
      "counter = 4481\n",
      "Finished adding CSX.csv data to the prepared_data_matrix!\n",
      "122 CTAS.csv\n",
      "counter = 4481\n",
      "Finished adding CTAS.csv data to the prepared_data_matrix!\n",
      "123 CTL.csv\n",
      "counter = 4481\n",
      "Finished adding CTL.csv data to the prepared_data_matrix!\n",
      "124 CTSH.csv\n",
      "counter = 4481\n",
      "Finished adding CTSH.csv data to the prepared_data_matrix!\n",
      "125 CTXS.csv\n",
      "counter = 4481\n",
      "Finished adding CTXS.csv data to the prepared_data_matrix!\n",
      "126 CVS.csv\n",
      "counter = 4481\n",
      "Finished adding CVS.csv data to the prepared_data_matrix!\n",
      "127 CVX.csv\n",
      "counter = 4481\n",
      "Finished adding CVX.csv data to the prepared_data_matrix!\n",
      "128 CXO.csv\n",
      "counter = 2679\n",
      "Finished adding CXO.csv data to the prepared_data_matrix!\n",
      "129 D.csv\n",
      "counter = 4481\n",
      "Finished adding D.csv data to the prepared_data_matrix!\n",
      "130 DAL.csv\n",
      "counter = 2743\n",
      "Finished adding DAL.csv data to the prepared_data_matrix!\n",
      "131 DE.csv\n",
      "counter = 4481\n",
      "Finished adding DE.csv data to the prepared_data_matrix!\n",
      "132 DFS.csv\n",
      "counter = 2714\n",
      "Finished adding DFS.csv data to the prepared_data_matrix!\n",
      "133 DG.csv\n",
      "counter = 2103\n",
      "Finished adding DG.csv data to the prepared_data_matrix!\n",
      "134 DGX.csv\n",
      "counter = 4481\n",
      "Finished adding DGX.csv data to the prepared_data_matrix!\n",
      "135 DHI.csv\n",
      "counter = 4481\n",
      "Finished adding DHI.csv data to the prepared_data_matrix!\n",
      "136 DHR.csv\n",
      "counter = 4481\n",
      "Finished adding DHR.csv data to the prepared_data_matrix!\n",
      "137 DIS.csv\n",
      "counter = 4481\n",
      "Finished adding DIS.csv data to the prepared_data_matrix!\n",
      "138 DISCA.csv\n",
      "counter = 3200\n",
      "Finished adding DISCA.csv data to the prepared_data_matrix!\n",
      "139 DISCK.csv\n",
      "counter = 2395\n",
      "Finished adding DISCK.csv data to the prepared_data_matrix!\n",
      "140 DISH.csv\n",
      "counter = 4481\n",
      "Finished adding DISH.csv data to the prepared_data_matrix!\n",
      "141 DLR.csv\n",
      "counter = 3373\n",
      "Finished adding DLR.csv data to the prepared_data_matrix!\n",
      "142 DLTR.csv\n",
      "counter = 4481\n",
      "Finished adding DLTR.csv data to the prepared_data_matrix!\n",
      "143 DOV.csv\n",
      "counter = 4481\n",
      "Finished adding DOV.csv data to the prepared_data_matrix!\n",
      "144 DRE.csv\n",
      "counter = 4481\n",
      "Finished adding DRE.csv data to the prepared_data_matrix!\n",
      "145 DRI.csv\n",
      "counter = 4481\n",
      "Finished adding DRI.csv data to the prepared_data_matrix!\n",
      "146 DTE.csv\n",
      "counter = 4481\n",
      "Finished adding DTE.csv data to the prepared_data_matrix!\n",
      "147 DUK.csv\n",
      "counter = 4481\n",
      "Finished adding DUK.csv data to the prepared_data_matrix!\n",
      "148 DVA.csv\n",
      "counter = 4481\n",
      "Finished adding DVA.csv data to the prepared_data_matrix!\n",
      "149 DVN.csv\n",
      "counter = 4481\n",
      "Finished adding DVN.csv data to the prepared_data_matrix!\n",
      "150 DWDP.csv\n",
      "counter = 140\n",
      "Finished adding DWDP.csv data to the prepared_data_matrix!\n",
      "151 DXC.csv\n",
      "counter = 246\n",
      "Finished adding DXC.csv data to the prepared_data_matrix!\n",
      "152 EA.csv\n",
      "counter = 4481\n",
      "Finished adding EA.csv data to the prepared_data_matrix!\n",
      "153 EBAY.csv\n",
      "counter = 4481\n",
      "Finished adding EBAY.csv data to the prepared_data_matrix!\n",
      "154 ECL.csv\n",
      "counter = 4481\n",
      "Finished adding ECL.csv data to the prepared_data_matrix!\n",
      "155 ED.csv\n",
      "counter = 4481\n",
      "Finished adding ED.csv data to the prepared_data_matrix!\n",
      "156 EFX.csv\n",
      "counter = 4481\n",
      "Finished adding EFX.csv data to the prepared_data_matrix!\n",
      "157 EIX.csv\n",
      "counter = 4481\n",
      "Finished adding EIX.csv data to the prepared_data_matrix!\n",
      "158 EL.csv\n",
      "counter = 4481\n",
      "Finished adding EL.csv data to the prepared_data_matrix!\n",
      "159 EMN.csv\n",
      "counter = 4481\n",
      "Finished adding EMN.csv data to the prepared_data_matrix!\n",
      "160 EMR.csv\n",
      "counter = 4481\n",
      "Finished adding EMR.csv data to the prepared_data_matrix!\n",
      "161 EOG.csv\n",
      "counter = 4481\n",
      "Finished adding EOG.csv data to the prepared_data_matrix!\n",
      "162 EQIX.csv\n",
      "counter = 4431\n",
      "Finished adding EQIX.csv data to the prepared_data_matrix!\n",
      "163 EQR.csv\n",
      "counter = 4481\n",
      "Finished adding EQR.csv data to the prepared_data_matrix!\n",
      "164 EQT.csv\n",
      "counter = 4481\n",
      "Finished adding EQT.csv data to the prepared_data_matrix!\n",
      "165 ES.csv\n",
      "counter = 4481\n",
      "Finished adding ES.csv data to the prepared_data_matrix!\n",
      "166 ESRX.csv\n",
      "counter = 4481\n",
      "Finished adding ESRX.csv data to the prepared_data_matrix!\n",
      "167 ESS.csv\n",
      "counter = 4481\n",
      "Finished adding ESS.csv data to the prepared_data_matrix!\n",
      "168 ETFC.csv\n",
      "counter = 4481\n",
      "Finished adding ETFC.csv data to the prepared_data_matrix!\n",
      "169 ETN.csv\n",
      "counter = 4481\n",
      "Finished adding ETN.csv data to the prepared_data_matrix!\n",
      "170 ETR.csv\n",
      "counter = 4481\n",
      "Finished adding ETR.csv data to the prepared_data_matrix!\n",
      "171 EVHC.csv\n",
      "counter = 1161\n",
      "Finished adding EVHC.csv data to the prepared_data_matrix!\n",
      "File not found!\n",
      "173 EW.csv\n",
      "counter = 4481\n",
      "Finished adding EW.csv data to the prepared_data_matrix!\n",
      "174 EXC.csv\n",
      "counter = 4481\n",
      "Finished adding EXC.csv data to the prepared_data_matrix!\n",
      "175 EXPD.csv\n",
      "counter = 4481\n",
      "Finished adding EXPD.csv data to the prepared_data_matrix!\n",
      "176 EXPE.csv\n",
      "counter = 3191\n",
      "Finished adding EXPE.csv data to the prepared_data_matrix!\n",
      "177 EXR.csv\n",
      "counter = 3426\n",
      "Finished adding EXR.csv data to the prepared_data_matrix!\n",
      "178 F.csv\n",
      "counter = 4481\n",
      "Finished adding F.csv data to the prepared_data_matrix!\n",
      "179 FAST.csv\n",
      "counter = 4481\n",
      "Finished adding FAST.csv data to the prepared_data_matrix!\n",
      "180 FB.csv\n",
      "counter = 1471\n",
      "Finished adding FB.csv data to the prepared_data_matrix!\n",
      "181 FBHS.csv\n",
      "counter = 1640\n",
      "Finished adding FBHS.csv data to the prepared_data_matrix!\n",
      "182 FCX.csv\n",
      "counter = 4481\n",
      "Finished adding FCX.csv data to the prepared_data_matrix!\n",
      "183 FDX.csv\n",
      "counter = 4481\n",
      "Finished adding FDX.csv data to the prepared_data_matrix!\n",
      "184 FE.csv\n",
      "counter = 4481\n",
      "Finished adding FE.csv data to the prepared_data_matrix!\n",
      "185 FFIV.csv\n",
      "counter = 4481\n",
      "Finished adding FFIV.csv data to the prepared_data_matrix!\n",
      "186 FIS.csv\n",
      "counter = 4216\n",
      "Finished adding FIS.csv data to the prepared_data_matrix!\n",
      "187 FISV.csv\n",
      "counter = 4481\n",
      "Finished adding FISV.csv data to the prepared_data_matrix!\n",
      "188 FITB.csv\n",
      "counter = 4481\n",
      "Finished adding FITB.csv data to the prepared_data_matrix!\n",
      "189 FL.csv\n",
      "counter = 4481\n",
      "Finished adding FL.csv data to the prepared_data_matrix!\n",
      "190 FLIR.csv\n",
      "counter = 4481\n",
      "Finished adding FLIR.csv data to the prepared_data_matrix!\n",
      "191 FLR.csv\n",
      "counter = 4353\n",
      "Finished adding FLR.csv data to the prepared_data_matrix!\n",
      "192 FLS.csv\n",
      "counter = 4481\n",
      "Finished adding FLS.csv data to the prepared_data_matrix!\n",
      "193 FLT.csv\n",
      "counter = 1830\n",
      "Finished adding FLT.csv data to the prepared_data_matrix!\n",
      "194 FMC.csv\n",
      "counter = 4481\n",
      "Finished adding FMC.csv data to the prepared_data_matrix!\n",
      "195 FOX.csv\n",
      "counter = 4481\n",
      "Finished adding FOX.csv data to the prepared_data_matrix!\n",
      "196 FOXA.csv\n",
      "counter = 4481\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Finished adding FOXA.csv data to the prepared_data_matrix!\n",
      "197 FRT.csv\n",
      "counter = 4481\n",
      "Finished adding FRT.csv data to the prepared_data_matrix!\n",
      "198 FTI.csv\n",
      "counter = 4219\n",
      "Finished adding FTI.csv data to the prepared_data_matrix!\n",
      "199 FTV.csv\n",
      "counter = 434\n",
      "Finished adding FTV.csv data to the prepared_data_matrix!\n",
      "200 GD.csv\n",
      "counter = 4481\n",
      "Finished adding GD.csv data to the prepared_data_matrix!\n",
      "201 GE.csv\n",
      "counter = 4481\n",
      "Finished adding GE.csv data to the prepared_data_matrix!\n",
      "202 GGP.csv\n",
      "counter = 4481\n",
      "Finished adding GGP.csv data to the prepared_data_matrix!\n",
      "203 GILD.csv\n",
      "counter = 4481\n",
      "Finished adding GILD.csv data to the prepared_data_matrix!\n",
      "204 GIS.csv\n",
      "counter = 4481\n",
      "Finished adding GIS.csv data to the prepared_data_matrix!\n",
      "205 GLW.csv\n",
      "counter = 4481\n",
      "Finished adding GLW.csv data to the prepared_data_matrix!\n",
      "206 GM.csv\n",
      "counter = 1848\n",
      "Finished adding GM.csv data to the prepared_data_matrix!\n",
      "207 GOOG.csv\n",
      "counter = 1006\n",
      "Finished adding GOOG.csv data to the prepared_data_matrix!\n",
      "208 GOOGL.csv\n",
      "counter = 3423\n",
      "Finished adding GOOGL.csv data to the prepared_data_matrix!\n",
      "209 GPC.csv\n",
      "counter = 4481\n",
      "Finished adding GPC.csv data to the prepared_data_matrix!\n",
      "210 GPN.csv\n",
      "counter = 4324\n",
      "Finished adding GPN.csv data to the prepared_data_matrix!\n",
      "211 GPS.csv\n",
      "counter = 4481\n",
      "Finished adding GPS.csv data to the prepared_data_matrix!\n",
      "212 GRMN.csv\n",
      "counter = 4348\n",
      "Finished adding GRMN.csv data to the prepared_data_matrix!\n",
      "213 GS.csv\n",
      "counter = 4481\n",
      "Finished adding GS.csv data to the prepared_data_matrix!\n",
      "214 GT.csv\n",
      "counter = 4481\n",
      "Finished adding GT.csv data to the prepared_data_matrix!\n",
      "215 GWW.csv\n",
      "counter = 4481\n",
      "Finished adding GWW.csv data to the prepared_data_matrix!\n",
      "216 HAL.csv\n",
      "counter = 4481\n",
      "Finished adding HAL.csv data to the prepared_data_matrix!\n",
      "217 HAS.csv\n",
      "counter = 4481\n",
      "Finished adding HAS.csv data to the prepared_data_matrix!\n",
      "218 HBAN.csv\n",
      "counter = 4481\n",
      "Finished adding HBAN.csv data to the prepared_data_matrix!\n",
      "219 HBI.csv\n",
      "counter = 2907\n",
      "Finished adding HBI.csv data to the prepared_data_matrix!\n",
      "220 HCA.csv\n",
      "counter = 1772\n",
      "Finished adding HCA.csv data to the prepared_data_matrix!\n",
      "221 HCP.csv\n",
      "counter = 4481\n",
      "Finished adding HCP.csv data to the prepared_data_matrix!\n",
      "222 HD.csv\n",
      "counter = 4481\n",
      "Finished adding HD.csv data to the prepared_data_matrix!\n",
      "223 HES.csv\n",
      "counter = 4481\n",
      "Finished adding HES.csv data to the prepared_data_matrix!\n",
      "224 HFC.csv\n",
      "counter = 4481\n",
      "Finished adding HFC.csv data to the prepared_data_matrix!\n",
      "225 HIG.csv\n",
      "counter = 4481\n",
      "Finished adding HIG.csv data to the prepared_data_matrix!\n",
      "226 HII.csv\n",
      "counter = 1764\n",
      "Finished adding HII.csv data to the prepared_data_matrix!\n",
      "227 HLT.csv\n",
      "counter = 193\n",
      "Finished adding HLT.csv data to the prepared_data_matrix!\n",
      "228 HOG.csv\n",
      "counter = 4481\n",
      "Finished adding HOG.csv data to the prepared_data_matrix!\n",
      "229 HOLX.csv\n",
      "counter = 4481\n",
      "Finished adding HOLX.csv data to the prepared_data_matrix!\n",
      "230 HON.csv\n",
      "counter = 4481\n",
      "Finished adding HON.csv data to the prepared_data_matrix!\n",
      "231 HP.csv\n",
      "counter = 4481\n",
      "Finished adding HP.csv data to the prepared_data_matrix!\n",
      "232 HPE.csv\n",
      "counter = 602\n",
      "Finished adding HPE.csv data to the prepared_data_matrix!\n",
      "233 HPQ.csv\n",
      "counter = 4481\n",
      "Finished adding HPQ.csv data to the prepared_data_matrix!\n",
      "234 HRB.csv\n",
      "counter = 4481\n",
      "Finished adding HRB.csv data to the prepared_data_matrix!\n",
      "235 HRL.csv\n",
      "counter = 4481\n",
      "Finished adding HRL.csv data to the prepared_data_matrix!\n",
      "236 HRS.csv\n",
      "counter = 4481\n",
      "Finished adding HRS.csv data to the prepared_data_matrix!\n",
      "237 HSIC.csv\n",
      "counter = 4481\n",
      "Finished adding HSIC.csv data to the prepared_data_matrix!\n",
      "238 HST.csv\n",
      "counter = 4481\n",
      "Finished adding HST.csv data to the prepared_data_matrix!\n",
      "239 HSY.csv\n",
      "counter = 4481\n",
      "Finished adding HSY.csv data to the prepared_data_matrix!\n",
      "240 HUM.csv\n",
      "counter = 4481\n",
      "Finished adding HUM.csv data to the prepared_data_matrix!\n",
      "241 IBM.csv\n",
      "counter = 4481\n",
      "Finished adding IBM.csv data to the prepared_data_matrix!\n",
      "242 ICE.csv\n",
      "counter = 3107\n",
      "Finished adding ICE.csv data to the prepared_data_matrix!\n",
      "243 IDXX.csv\n",
      "counter = 4481\n",
      "Finished adding IDXX.csv data to the prepared_data_matrix!\n",
      "244 IFF.csv\n",
      "counter = 4481\n",
      "Finished adding IFF.csv data to the prepared_data_matrix!\n",
      "245 ILMN.csv\n",
      "counter = 4441\n",
      "Finished adding ILMN.csv data to the prepared_data_matrix!\n",
      "246 INCY.csv\n",
      "counter = 4481\n",
      "Finished adding INCY.csv data to the prepared_data_matrix!\n",
      "247 INFO.csv\n",
      "counter = 204\n",
      "Finished adding INFO.csv data to the prepared_data_matrix!\n",
      "248 INTC.csv\n",
      "counter = 4481\n",
      "Finished adding INTC.csv data to the prepared_data_matrix!\n",
      "249 INTU.csv\n",
      "counter = 4481\n",
      "Finished adding INTU.csv data to the prepared_data_matrix!\n",
      "250 IP.csv\n",
      "counter = 4481\n",
      "Finished adding IP.csv data to the prepared_data_matrix!\n",
      "251 IPG.csv\n",
      "counter = 4481\n",
      "Finished adding IPG.csv data to the prepared_data_matrix!\n",
      "252 IPGP.csv\n",
      "counter = 2838\n",
      "Finished adding IPGP.csv data to the prepared_data_matrix!\n",
      "253 IQV.csv\n",
      "counter = 89\n",
      "Finished adding IQV.csv data to the prepared_data_matrix!\n",
      "254 IR.csv\n",
      "counter = 4481\n",
      "Finished adding IR.csv data to the prepared_data_matrix!\n",
      "255 IRM.csv\n",
      "counter = 4481\n",
      "Finished adding IRM.csv data to the prepared_data_matrix!\n",
      "256 ISRG.csv\n",
      "counter = 4470\n",
      "Finished adding ISRG.csv data to the prepared_data_matrix!\n",
      "257 IT.csv\n",
      "counter = 4481\n",
      "Finished adding IT.csv data to the prepared_data_matrix!\n",
      "258 ITW.csv\n",
      "counter = 4481\n",
      "Finished adding ITW.csv data to the prepared_data_matrix!\n",
      "259 IVZ.csv\n",
      "counter = 4481\n",
      "Finished adding IVZ.csv data to the prepared_data_matrix!\n",
      "260 JBHT.csv\n",
      "counter = 4481\n",
      "Finished adding JBHT.csv data to the prepared_data_matrix!\n",
      "261 JCI.csv\n",
      "counter = 4481\n",
      "Finished adding JCI.csv data to the prepared_data_matrix!\n",
      "262 JEC.csv\n",
      "counter = 4481\n",
      "Finished adding JEC.csv data to the prepared_data_matrix!\n",
      "File not found!\n",
      "264 JNJ.csv\n",
      "counter = 4481\n",
      "Finished adding JNJ.csv data to the prepared_data_matrix!\n",
      "265 JNPR.csv\n",
      "counter = 4481\n",
      "Finished adding JNPR.csv data to the prepared_data_matrix!\n",
      "266 JPM.csv\n",
      "counter = 4481\n",
      "Finished adding JPM.csv data to the prepared_data_matrix!\n",
      "267 JWN.csv\n",
      "counter = 4481\n",
      "Finished adding JWN.csv data to the prepared_data_matrix!\n",
      "268 K.csv\n",
      "counter = 4481\n",
      "Finished adding K.csv data to the prepared_data_matrix!\n",
      "269 KEY.csv\n",
      "counter = 4481\n",
      "Finished adding KEY.csv data to the prepared_data_matrix!\n",
      "270 KHC.csv\n",
      "counter = 686\n",
      "Finished adding KHC.csv data to the prepared_data_matrix!\n",
      "271 KIM.csv\n",
      "counter = 4481\n",
      "Finished adding KIM.csv data to the prepared_data_matrix!\n",
      "272 KLAC.csv\n",
      "counter = 4481\n",
      "Finished adding KLAC.csv data to the prepared_data_matrix!\n",
      "273 KMB.csv\n",
      "counter = 4481\n",
      "Finished adding KMB.csv data to the prepared_data_matrix!\n",
      "274 KMI.csv\n",
      "counter = 1790\n",
      "Finished adding KMI.csv data to the prepared_data_matrix!\n",
      "275 KMX.csv\n",
      "counter = 4481\n",
      "Finished adding KMX.csv data to the prepared_data_matrix!\n",
      "276 KO.csv\n",
      "counter = 4481\n",
      "Finished adding KO.csv data to the prepared_data_matrix!\n",
      "277 KORS.csv\n",
      "counter = 1577\n",
      "Finished adding KORS.csv data to the prepared_data_matrix!\n",
      "278 KR.csv\n",
      "counter = 4481\n",
      "Finished adding KR.csv data to the prepared_data_matrix!\n",
      "279 KSS.csv\n",
      "counter = 4481\n",
      "Finished adding KSS.csv data to the prepared_data_matrix!\n",
      "280 KSU.csv\n",
      "counter = 4481\n",
      "Finished adding KSU.csv data to the prepared_data_matrix!\n",
      "281 L.csv\n",
      "counter = 4481\n",
      "Finished adding L.csv data to the prepared_data_matrix!\n",
      "282 LB.csv\n",
      "counter = 4481\n",
      "Finished adding LB.csv data to the prepared_data_matrix!\n",
      "283 LEG.csv\n",
      "counter = 4481\n",
      "Finished adding LEG.csv data to the prepared_data_matrix!\n",
      "284 LEN.csv\n",
      "counter = 4481\n",
      "Finished adding LEN.csv data to the prepared_data_matrix!\n",
      "285 LH.csv\n",
      "counter = 4481\n",
      "Finished adding LH.csv data to the prepared_data_matrix!\n",
      "286 LKQ.csv\n",
      "counter = 3642\n",
      "Finished adding LKQ.csv data to the prepared_data_matrix!\n",
      "287 LLL.csv\n",
      "counter = 4481\n",
      "Finished adding LLL.csv data to the prepared_data_matrix!\n",
      "288 LLY.csv\n",
      "counter = 4481\n",
      "Finished adding LLY.csv data to the prepared_data_matrix!\n",
      "289 LMT.csv\n",
      "counter = 4481\n",
      "Finished adding LMT.csv data to the prepared_data_matrix!\n",
      "290 LNC.csv\n",
      "counter = 4481\n",
      "Finished adding LNC.csv data to the prepared_data_matrix!\n",
      "291 LNT.csv\n",
      "counter = 4481\n",
      "Finished adding LNT.csv data to the prepared_data_matrix!\n",
      "292 LOW.csv\n",
      "counter = 4481\n",
      "Finished adding LOW.csv data to the prepared_data_matrix!\n",
      "293 LRCX.csv\n",
      "counter = 4481\n",
      "Finished adding LRCX.csv data to the prepared_data_matrix!\n",
      "294 LUV.csv\n",
      "counter = 4481\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Finished adding LUV.csv data to the prepared_data_matrix!\n",
      "295 LYB.csv\n",
      "counter = 1991\n",
      "Finished adding LYB.csv data to the prepared_data_matrix!\n",
      "296 M.csv\n",
      "counter = 4481\n",
      "Finished adding M.csv data to the prepared_data_matrix!\n",
      "297 MA.csv\n",
      "counter = 2977\n",
      "Finished adding MA.csv data to the prepared_data_matrix!\n",
      "298 MAA.csv\n",
      "counter = 4481\n",
      "Finished adding MAA.csv data to the prepared_data_matrix!\n",
      "299 MAC.csv\n",
      "counter = 4481\n",
      "Finished adding MAC.csv data to the prepared_data_matrix!\n",
      "300 MAR.csv\n",
      "counter = 4481\n",
      "Finished adding MAR.csv data to the prepared_data_matrix!\n",
      "301 MAS.csv\n",
      "counter = 4481\n",
      "Finished adding MAS.csv data to the prepared_data_matrix!\n",
      "302 MAT.csv\n",
      "counter = 4481\n",
      "Finished adding MAT.csv data to the prepared_data_matrix!\n",
      "303 MCD.csv\n",
      "counter = 4481\n",
      "Finished adding MCD.csv data to the prepared_data_matrix!\n",
      "304 MCHP.csv\n",
      "counter = 4481\n",
      "Finished adding MCHP.csv data to the prepared_data_matrix!\n",
      "305 MCK.csv\n",
      "counter = 4481\n",
      "Finished adding MCK.csv data to the prepared_data_matrix!\n",
      "306 MCO.csv\n",
      "counter = 4481\n",
      "Finished adding MCO.csv data to the prepared_data_matrix!\n",
      "307 MDLZ.csv\n",
      "counter = 4221\n",
      "Finished adding MDLZ.csv data to the prepared_data_matrix!\n",
      "308 MDT.csv\n",
      "counter = 4481\n",
      "Finished adding MDT.csv data to the prepared_data_matrix!\n",
      "309 MET.csv\n",
      "counter = 4481\n",
      "Finished adding MET.csv data to the prepared_data_matrix!\n",
      "310 MGM.csv\n",
      "counter = 4481\n",
      "Finished adding MGM.csv data to the prepared_data_matrix!\n",
      "311 MHK.csv\n",
      "counter = 4481\n",
      "Finished adding MHK.csv data to the prepared_data_matrix!\n",
      "312 MKC.csv\n",
      "counter = 4481\n",
      "Finished adding MKC.csv data to the prepared_data_matrix!\n",
      "313 MLM.csv\n",
      "counter = 4481\n",
      "Finished adding MLM.csv data to the prepared_data_matrix!\n",
      "314 MMC.csv\n",
      "counter = 4481\n",
      "Finished adding MMC.csv data to the prepared_data_matrix!\n",
      "315 MMM.csv\n",
      "counter = 4481\n",
      "Finished adding MMM.csv data to the prepared_data_matrix!\n",
      "316 MNST.csv\n",
      "counter = 4481\n",
      "Finished adding MNST.csv data to the prepared_data_matrix!\n",
      "317 MO.csv\n",
      "counter = 4481\n",
      "Finished adding MO.csv data to the prepared_data_matrix!\n",
      "318 MOS.csv\n",
      "counter = 4481\n",
      "Finished adding MOS.csv data to the prepared_data_matrix!\n",
      "319 MPC.csv\n",
      "counter = 1698\n",
      "Finished adding MPC.csv data to the prepared_data_matrix!\n",
      "320 MRK.csv\n",
      "counter = 4481\n",
      "Finished adding MRK.csv data to the prepared_data_matrix!\n",
      "321 MRO.csv\n",
      "counter = 4481\n",
      "Finished adding MRO.csv data to the prepared_data_matrix!\n",
      "322 MS.csv\n",
      "counter = 4481\n",
      "Finished adding MS.csv data to the prepared_data_matrix!\n",
      "323 MSCI.csv\n",
      "counter = 2606\n",
      "Finished adding MSCI.csv data to the prepared_data_matrix!\n",
      "324 MSFT.csv\n",
      "counter = 4481\n",
      "Finished adding MSFT.csv data to the prepared_data_matrix!\n",
      "325 MSI.csv\n",
      "counter = 4481\n",
      "Finished adding MSI.csv data to the prepared_data_matrix!\n",
      "326 MTB.csv\n",
      "counter = 4481\n",
      "Finished adding MTB.csv data to the prepared_data_matrix!\n",
      "327 MTD.csv\n",
      "counter = 4481\n",
      "Finished adding MTD.csv data to the prepared_data_matrix!\n",
      "328 MU.csv\n",
      "counter = 4481\n",
      "Finished adding MU.csv data to the prepared_data_matrix!\n",
      "329 MYL.csv\n",
      "counter = 4481\n",
      "Finished adding MYL.csv data to the prepared_data_matrix!\n",
      "330 NBL.csv\n",
      "counter = 4481\n",
      "Finished adding NBL.csv data to the prepared_data_matrix!\n",
      "331 NCLH.csv\n",
      "counter = 1304\n",
      "Finished adding NCLH.csv data to the prepared_data_matrix!\n",
      "332 NDAQ.csv\n",
      "counter = 3961\n",
      "Finished adding NDAQ.csv data to the prepared_data_matrix!\n",
      "333 NEE.csv\n",
      "counter = 4481\n",
      "Finished adding NEE.csv data to the prepared_data_matrix!\n",
      "334 NEM.csv\n",
      "counter = 4481\n",
      "Finished adding NEM.csv data to the prepared_data_matrix!\n",
      "335 NFLX.csv\n",
      "counter = 3987\n",
      "Finished adding NFLX.csv data to the prepared_data_matrix!\n",
      "336 NFX.csv\n",
      "counter = 4481\n",
      "Finished adding NFX.csv data to the prepared_data_matrix!\n",
      "337 NI.csv\n",
      "counter = 4481\n",
      "Finished adding NI.csv data to the prepared_data_matrix!\n",
      "338 NKE.csv\n",
      "counter = 4481\n",
      "Finished adding NKE.csv data to the prepared_data_matrix!\n",
      "339 NKTR.csv\n",
      "counter = 4481\n",
      "Finished adding NKTR.csv data to the prepared_data_matrix!\n",
      "340 NLSN.csv\n",
      "counter = 1801\n",
      "Finished adding NLSN.csv data to the prepared_data_matrix!\n",
      "341 NOC.csv\n",
      "counter = 4481\n",
      "Finished adding NOC.csv data to the prepared_data_matrix!\n",
      "342 NOV.csv\n",
      "counter = 4481\n",
      "Finished adding NOV.csv data to the prepared_data_matrix!\n",
      "343 NRG.csv\n",
      "counter = 3602\n",
      "Finished adding NRG.csv data to the prepared_data_matrix!\n",
      "344 NSC.csv\n",
      "counter = 4481\n",
      "Finished adding NSC.csv data to the prepared_data_matrix!\n",
      "345 NTAP.csv\n",
      "counter = 4481\n",
      "Finished adding NTAP.csv data to the prepared_data_matrix!\n",
      "346 NTRS.csv\n",
      "counter = 4481\n",
      "Finished adding NTRS.csv data to the prepared_data_matrix!\n",
      "347 NUE.csv\n",
      "counter = 4481\n",
      "Finished adding NUE.csv data to the prepared_data_matrix!\n",
      "348 NVDA.csv\n",
      "counter = 4481\n",
      "Finished adding NVDA.csv data to the prepared_data_matrix!\n",
      "349 NWL.csv\n",
      "counter = 4481\n",
      "Finished adding NWL.csv data to the prepared_data_matrix!\n",
      "350 NWS.csv\n",
      "counter = 1200\n",
      "Finished adding NWS.csv data to the prepared_data_matrix!\n",
      "351 NWSA.csv\n",
      "counter = 1200\n",
      "Finished adding NWSA.csv data to the prepared_data_matrix!\n",
      "352 O.csv\n",
      "counter = 4481\n",
      "Finished adding O.csv data to the prepared_data_matrix!\n",
      "353 OKE.csv\n",
      "counter = 4481\n",
      "Finished adding OKE.csv data to the prepared_data_matrix!\n",
      "354 OMC.csv\n",
      "counter = 4481\n",
      "Finished adding OMC.csv data to the prepared_data_matrix!\n",
      "355 ORCL.csv\n",
      "counter = 4481\n",
      "Finished adding ORCL.csv data to the prepared_data_matrix!\n",
      "356 ORLY.csv\n",
      "counter = 4481\n",
      "Finished adding ORLY.csv data to the prepared_data_matrix!\n",
      "357 OXY.csv\n",
      "counter = 4481\n",
      "Finished adding OXY.csv data to the prepared_data_matrix!\n",
      "358 PAYX.csv\n",
      "counter = 4481\n",
      "Finished adding PAYX.csv data to the prepared_data_matrix!\n",
      "359 PBCT.csv\n",
      "counter = 4481\n",
      "Finished adding PBCT.csv data to the prepared_data_matrix!\n",
      "360 PCAR.csv\n",
      "counter = 4481\n",
      "Finished adding PCAR.csv data to the prepared_data_matrix!\n",
      "361 PCG.csv\n",
      "counter = 4481\n",
      "Finished adding PCG.csv data to the prepared_data_matrix!\n",
      "362 PEG.csv\n",
      "counter = 4481\n",
      "Finished adding PEG.csv data to the prepared_data_matrix!\n",
      "363 PEP.csv\n",
      "counter = 4481\n",
      "Finished adding PEP.csv data to the prepared_data_matrix!\n",
      "364 PFE.csv\n",
      "counter = 4481\n",
      "Finished adding PFE.csv data to the prepared_data_matrix!\n",
      "365 PFG.csv\n",
      "counter = 4133\n",
      "Finished adding PFG.csv data to the prepared_data_matrix!\n",
      "366 PG.csv\n",
      "counter = 4481\n",
      "Finished adding PG.csv data to the prepared_data_matrix!\n",
      "367 PGR.csv\n",
      "counter = 4481\n",
      "Finished adding PGR.csv data to the prepared_data_matrix!\n",
      "368 PH.csv\n",
      "counter = 4481\n",
      "Finished adding PH.csv data to the prepared_data_matrix!\n",
      "369 PHM.csv\n",
      "counter = 4481\n",
      "Finished adding PHM.csv data to the prepared_data_matrix!\n",
      "370 PKG.csv\n",
      "counter = 4481\n",
      "Finished adding PKG.csv data to the prepared_data_matrix!\n",
      "371 PKI.csv\n",
      "counter = 4481\n",
      "Finished adding PKI.csv data to the prepared_data_matrix!\n",
      "372 PLD.csv\n",
      "counter = 4481\n",
      "Finished adding PLD.csv data to the prepared_data_matrix!\n",
      "373 PM.csv\n",
      "counter = 2524\n",
      "Finished adding PM.csv data to the prepared_data_matrix!\n",
      "374 PNC.csv\n",
      "counter = 4481\n",
      "Finished adding PNC.csv data to the prepared_data_matrix!\n",
      "375 PNR.csv\n",
      "counter = 4481\n",
      "Finished adding PNR.csv data to the prepared_data_matrix!\n",
      "376 PNW.csv\n",
      "counter = 4481\n",
      "Finished adding PNW.csv data to the prepared_data_matrix!\n",
      "377 PPG.csv\n",
      "counter = 230\n",
      "Finished adding PPG.csv data to the prepared_data_matrix!\n",
      "378 PPL.csv\n",
      "counter = 4481\n",
      "Finished adding PPL.csv data to the prepared_data_matrix!\n",
      "379 PRGO.csv\n",
      "counter = 4481\n",
      "Finished adding PRGO.csv data to the prepared_data_matrix!\n",
      "380 PRU.csv\n",
      "counter = 4097\n",
      "Finished adding PRU.csv data to the prepared_data_matrix!\n",
      "381 PSA.csv\n",
      "counter = 4481\n",
      "Finished adding PSA.csv data to the prepared_data_matrix!\n",
      "382 PSX.csv\n",
      "counter = 1497\n",
      "Finished adding PSX.csv data to the prepared_data_matrix!\n",
      "383 PVH.csv\n",
      "counter = 4481\n",
      "Finished adding PVH.csv data to the prepared_data_matrix!\n",
      "384 PWR.csv\n",
      "counter = 4481\n",
      "Finished adding PWR.csv data to the prepared_data_matrix!\n",
      "385 PX.csv\n",
      "counter = 4481\n",
      "Finished adding PX.csv data to the prepared_data_matrix!\n",
      "386 PXD.csv\n",
      "counter = 4481\n",
      "Finished adding PXD.csv data to the prepared_data_matrix!\n",
      "387 PYPL.csv\n",
      "counter = 676\n",
      "Finished adding PYPL.csv data to the prepared_data_matrix!\n",
      "388 QCOM.csv\n",
      "counter = 4481\n",
      "Finished adding QCOM.csv data to the prepared_data_matrix!\n",
      "389 QRVO.csv\n",
      "counter = 812\n",
      "Finished adding QRVO.csv data to the prepared_data_matrix!\n",
      "390 RCL.csv\n",
      "counter = 4481\n",
      "Finished adding RCL.csv data to the prepared_data_matrix!\n",
      "391 RE.csv\n",
      "counter = 4481\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Finished adding RE.csv data to the prepared_data_matrix!\n",
      "392 REG.csv\n",
      "counter = 4481\n",
      "Finished adding REG.csv data to the prepared_data_matrix!\n",
      "393 REGN.csv\n",
      "counter = 4481\n",
      "Finished adding REGN.csv data to the prepared_data_matrix!\n",
      "394 RF.csv\n",
      "counter = 4481\n",
      "Finished adding RF.csv data to the prepared_data_matrix!\n",
      "395 RHI.csv\n",
      "counter = 4481\n",
      "Finished adding RHI.csv data to the prepared_data_matrix!\n",
      "396 RHT.csv\n",
      "counter = 4481\n",
      "Finished adding RHT.csv data to the prepared_data_matrix!\n",
      "397 RJF.csv\n",
      "counter = 4481\n",
      "Finished adding RJF.csv data to the prepared_data_matrix!\n",
      "398 RL.csv\n",
      "counter = 4481\n",
      "Finished adding RL.csv data to the prepared_data_matrix!\n",
      "399 RMD.csv\n",
      "counter = 4481\n",
      "Finished adding RMD.csv data to the prepared_data_matrix!\n",
      "400 ROK.csv\n",
      "counter = 4481\n",
      "Finished adding ROK.csv data to the prepared_data_matrix!\n",
      "401 ROP.csv\n",
      "counter = 4481\n",
      "Finished adding ROP.csv data to the prepared_data_matrix!\n",
      "402 ROST.csv\n",
      "counter = 4481\n",
      "Finished adding ROST.csv data to the prepared_data_matrix!\n",
      "403 RSG.csv\n",
      "counter = 4481\n",
      "Finished adding RSG.csv data to the prepared_data_matrix!\n",
      "404 RTN.csv\n",
      "counter = 4481\n",
      "Finished adding RTN.csv data to the prepared_data_matrix!\n",
      "405 SBAC.csv\n",
      "counter = 4481\n",
      "Finished adding SBAC.csv data to the prepared_data_matrix!\n",
      "406 SBUX.csv\n",
      "counter = 4481\n",
      "Finished adding SBUX.csv data to the prepared_data_matrix!\n",
      "407 SCG.csv\n",
      "counter = 4481\n",
      "Finished adding SCG.csv data to the prepared_data_matrix!\n",
      "408 SCHW.csv\n",
      "counter = 4481\n",
      "Finished adding SCHW.csv data to the prepared_data_matrix!\n",
      "409 SEE.csv\n",
      "counter = 4481\n",
      "Finished adding SEE.csv data to the prepared_data_matrix!\n",
      "410 SHW.csv\n",
      "counter = 4481\n",
      "Finished adding SHW.csv data to the prepared_data_matrix!\n",
      "411 SIVB.csv\n",
      "counter = 4481\n",
      "Finished adding SIVB.csv data to the prepared_data_matrix!\n",
      "412 SJM.csv\n",
      "counter = 4481\n",
      "Finished adding SJM.csv data to the prepared_data_matrix!\n",
      "413 SLB.csv\n",
      "counter = 4481\n",
      "Finished adding SLB.csv data to the prepared_data_matrix!\n",
      "414 SLG.csv\n",
      "counter = 4481\n",
      "Finished adding SLG.csv data to the prepared_data_matrix!\n",
      "415 SNA.csv\n",
      "counter = 4481\n",
      "Finished adding SNA.csv data to the prepared_data_matrix!\n",
      "416 SNPS.csv\n",
      "counter = 4481\n",
      "Finished adding SNPS.csv data to the prepared_data_matrix!\n",
      "417 SO.csv\n",
      "counter = 4481\n",
      "Finished adding SO.csv data to the prepared_data_matrix!\n",
      "418 SPG.csv\n",
      "counter = 4481\n",
      "Finished adding SPG.csv data to the prepared_data_matrix!\n",
      "419 SPGI.csv\n",
      "counter = 480\n",
      "Finished adding SPGI.csv data to the prepared_data_matrix!\n",
      "420 SRCL.csv\n",
      "counter = 4481\n",
      "Finished adding SRCL.csv data to the prepared_data_matrix!\n",
      "421 SRE.csv\n",
      "counter = 4481\n",
      "Finished adding SRE.csv data to the prepared_data_matrix!\n",
      "422 STI.csv\n",
      "counter = 4481\n",
      "Finished adding STI.csv data to the prepared_data_matrix!\n",
      "423 STT.csv\n",
      "counter = 4481\n",
      "Finished adding STT.csv data to the prepared_data_matrix!\n",
      "424 STX.csv\n",
      "counter = 3847\n",
      "Finished adding STX.csv data to the prepared_data_matrix!\n",
      "425 STZ.csv\n",
      "counter = 4481\n",
      "Finished adding STZ.csv data to the prepared_data_matrix!\n",
      "426 SWK.csv\n",
      "counter = 4481\n",
      "Finished adding SWK.csv data to the prepared_data_matrix!\n",
      "427 SWKS.csv\n",
      "counter = 4481\n",
      "Finished adding SWKS.csv data to the prepared_data_matrix!\n",
      "428 SYF.csv\n",
      "counter = 919\n",
      "Finished adding SYF.csv data to the prepared_data_matrix!\n",
      "429 SYK.csv\n",
      "counter = 4481\n",
      "Finished adding SYK.csv data to the prepared_data_matrix!\n",
      "430 SYMC.csv\n",
      "counter = 4481\n",
      "Finished adding SYMC.csv data to the prepared_data_matrix!\n",
      "431 SYY.csv\n",
      "counter = 4481\n",
      "Finished adding SYY.csv data to the prepared_data_matrix!\n",
      "432 T.csv\n",
      "counter = 4481\n",
      "Finished adding T.csv data to the prepared_data_matrix!\n",
      "433 TAP.csv\n",
      "counter = 4481\n",
      "Finished adding TAP.csv data to the prepared_data_matrix!\n",
      "434 TDG.csv\n",
      "counter = 3028\n",
      "Finished adding TDG.csv data to the prepared_data_matrix!\n",
      "435 TEL.csv\n",
      "counter = 2714\n",
      "Finished adding TEL.csv data to the prepared_data_matrix!\n",
      "436 TGT.csv\n",
      "counter = 4481\n",
      "Finished adding TGT.csv data to the prepared_data_matrix!\n",
      "437 TIF.csv\n",
      "counter = 4481\n",
      "Finished adding TIF.csv data to the prepared_data_matrix!\n",
      "438 TJX.csv\n",
      "counter = 4481\n",
      "Finished adding TJX.csv data to the prepared_data_matrix!\n",
      "439 TMK.csv\n",
      "counter = 4481\n",
      "Finished adding TMK.csv data to the prepared_data_matrix!\n",
      "440 TMO.csv\n",
      "counter = 4481\n",
      "Finished adding TMO.csv data to the prepared_data_matrix!\n",
      "441 TPR.csv\n",
      "counter = 99\n",
      "Finished adding TPR.csv data to the prepared_data_matrix!\n",
      "442 TRIP.csv\n",
      "counter = 1583\n",
      "Finished adding TRIP.csv data to the prepared_data_matrix!\n",
      "443 TROW.csv\n",
      "counter = 4481\n",
      "Finished adding TROW.csv data to the prepared_data_matrix!\n",
      "444 TRV.csv\n",
      "counter = 230\n",
      "Finished adding TRV.csv data to the prepared_data_matrix!\n",
      "445 TSCO.csv\n",
      "counter = 4481\n",
      "Finished adding TSCO.csv data to the prepared_data_matrix!\n",
      "446 TSN.csv\n",
      "counter = 4481\n",
      "Finished adding TSN.csv data to the prepared_data_matrix!\n",
      "447 TSS.csv\n",
      "counter = 4481\n",
      "Finished adding TSS.csv data to the prepared_data_matrix!\n",
      "448 TTWO.csv\n",
      "counter = 4481\n",
      "Finished adding TTWO.csv data to the prepared_data_matrix!\n",
      "449 TWTR.csv\n",
      "counter = 1101\n",
      "Finished adding TWTR.csv data to the prepared_data_matrix!\n",
      "450 TXN.csv\n",
      "counter = 4481\n",
      "Finished adding TXN.csv data to the prepared_data_matrix!\n",
      "451 TXT.csv\n",
      "counter = 4481\n",
      "Finished adding TXT.csv data to the prepared_data_matrix!\n",
      "452 UA.csv\n",
      "counter = 494\n",
      "Finished adding UA.csv data to the prepared_data_matrix!\n",
      "453 UAA.csv\n",
      "counter = 3106\n",
      "Finished adding UAA.csv data to the prepared_data_matrix!\n",
      "454 UAL.csv\n",
      "counter = 3054\n",
      "Finished adding UAL.csv data to the prepared_data_matrix!\n",
      "455 UDR.csv\n",
      "counter = 4481\n",
      "Finished adding UDR.csv data to the prepared_data_matrix!\n",
      "456 UHS.csv\n",
      "counter = 4481\n",
      "Finished adding UHS.csv data to the prepared_data_matrix!\n",
      "457 ULTA.csv\n",
      "counter = 2621\n",
      "Finished adding ULTA.csv data to the prepared_data_matrix!\n",
      "458 UNH.csv\n",
      "counter = 4481\n",
      "Finished adding UNH.csv data to the prepared_data_matrix!\n",
      "459 UNM.csv\n",
      "counter = 4481\n",
      "Finished adding UNM.csv data to the prepared_data_matrix!\n",
      "460 UNP.csv\n",
      "counter = 4481\n",
      "Finished adding UNP.csv data to the prepared_data_matrix!\n",
      "461 UPS.csv\n",
      "counter = 4481\n",
      "Finished adding UPS.csv data to the prepared_data_matrix!\n",
      "462 URI.csv\n",
      "counter = 4481\n",
      "Finished adding URI.csv data to the prepared_data_matrix!\n",
      "463 USB.csv\n",
      "counter = 4481\n",
      "Finished adding USB.csv data to the prepared_data_matrix!\n",
      "464 UTX.csv\n",
      "counter = 4481\n",
      "Finished adding UTX.csv data to the prepared_data_matrix!\n",
      "465 V.csv\n",
      "counter = 2522\n",
      "Finished adding V.csv data to the prepared_data_matrix!\n",
      "466 VAR.csv\n",
      "counter = 4481\n",
      "Finished adding VAR.csv data to the prepared_data_matrix!\n",
      "467 VFC.csv\n",
      "counter = 4481\n",
      "Finished adding VFC.csv data to the prepared_data_matrix!\n",
      "468 VIAB.csv\n",
      "counter = 3096\n",
      "Finished adding VIAB.csv data to the prepared_data_matrix!\n",
      "469 VLO.csv\n",
      "counter = 4481\n",
      "Finished adding VLO.csv data to the prepared_data_matrix!\n",
      "470 VMC.csv\n",
      "counter = 4481\n",
      "Finished adding VMC.csv data to the prepared_data_matrix!\n",
      "471 VNO.csv\n",
      "counter = 4481\n",
      "Finished adding VNO.csv data to the prepared_data_matrix!\n",
      "472 VRSK.csv\n",
      "counter = 2130\n",
      "Finished adding VRSK.csv data to the prepared_data_matrix!\n",
      "473 VRSN.csv\n",
      "counter = 4481\n",
      "Finished adding VRSN.csv data to the prepared_data_matrix!\n",
      "474 VRTX.csv\n",
      "counter = 4481\n",
      "Finished adding VRTX.csv data to the prepared_data_matrix!\n",
      "475 VTR.csv\n",
      "counter = 4481\n",
      "Finished adding VTR.csv data to the prepared_data_matrix!\n",
      "476 VZ.csv\n",
      "counter = 4481\n",
      "Finished adding VZ.csv data to the prepared_data_matrix!\n",
      "477 WAT.csv\n",
      "counter = 4481\n",
      "Finished adding WAT.csv data to the prepared_data_matrix!\n",
      "478 WBA.csv\n",
      "counter = 4481\n",
      "Finished adding WBA.csv data to the prepared_data_matrix!\n",
      "479 WDC.csv\n",
      "counter = 4481\n",
      "Finished adding WDC.csv data to the prepared_data_matrix!\n",
      "480 WEC.csv\n",
      "counter = 4481\n",
      "Finished adding WEC.csv data to the prepared_data_matrix!\n",
      "481 WELL.csv\n",
      "counter = 13\n",
      "Finished adding WELL.csv data to the prepared_data_matrix!\n",
      "482 WFC.csv\n",
      "counter = 4481\n",
      "Finished adding WFC.csv data to the prepared_data_matrix!\n",
      "483 WHR.csv\n",
      "counter = 4481\n",
      "Finished adding WHR.csv data to the prepared_data_matrix!\n",
      "484 WLTW.csv\n",
      "counter = 559\n",
      "Finished adding WLTW.csv data to the prepared_data_matrix!\n",
      "485 WM.csv\n",
      "counter = 4481\n",
      "Finished adding WM.csv data to the prepared_data_matrix!\n",
      "486 WMB.csv\n",
      "counter = 4481\n",
      "Finished adding WMB.csv data to the prepared_data_matrix!\n",
      "487 WMT.csv\n",
      "counter = 4481\n",
      "Finished adding WMT.csv data to the prepared_data_matrix!\n",
      "488 WRK.csv\n",
      "counter = 693\n",
      "Finished adding WRK.csv data to the prepared_data_matrix!\n",
      "489 WU.csv\n",
      "counter = 2889\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Finished adding WU.csv data to the prepared_data_matrix!\n",
      "490 WY.csv\n",
      "counter = 4481\n",
      "Finished adding WY.csv data to the prepared_data_matrix!\n",
      "491 WYNN.csv\n",
      "counter = 3879\n",
      "Finished adding WYNN.csv data to the prepared_data_matrix!\n",
      "492 XEC.csv\n",
      "counter = 3901\n",
      "Finished adding XEC.csv data to the prepared_data_matrix!\n",
      "493 XEL.csv\n",
      "counter = 4481\n",
      "Finished adding XEL.csv data to the prepared_data_matrix!\n",
      "494 XL.csv\n",
      "counter = 4481\n",
      "Finished adding XL.csv data to the prepared_data_matrix!\n",
      "495 XLNX.csv\n",
      "counter = 4481\n",
      "Finished adding XLNX.csv data to the prepared_data_matrix!\n",
      "496 XOM.csv\n",
      "counter = 4481\n",
      "Finished adding XOM.csv data to the prepared_data_matrix!\n",
      "497 XRAY.csv\n",
      "counter = 4481\n",
      "Finished adding XRAY.csv data to the prepared_data_matrix!\n",
      "498 XRX.csv\n",
      "counter = 4481\n",
      "Finished adding XRX.csv data to the prepared_data_matrix!\n",
      "499 XYL.csv\n",
      "counter = 1621\n",
      "Finished adding XYL.csv data to the prepared_data_matrix!\n",
      "500 YUM.csv\n",
      "counter = 4481\n",
      "Finished adding YUM.csv data to the prepared_data_matrix!\n",
      "501 ZBH.csv\n",
      "counter = 4192\n",
      "Finished adding ZBH.csv data to the prepared_data_matrix!\n",
      "502 ZION.csv\n",
      "counter = 4481\n",
      "Finished adding ZION.csv data to the prepared_data_matrix!\n",
      "503 ZTS.csv\n",
      "counter = 1295\n",
      "Finished adding ZTS.csv data to the prepared_data_matrix!\n",
      "Done creating prepared_data_matrix!\n"
     ]
    }
   ],
   "source": [
    "import os.path   # To check whether a file exist\n",
    "\n",
    "for index in range (len(sp500_components) - 1):\n",
    "    \n",
    "    stock_symbol = str(sp500_components['Symbol'][index])    # Get the stock symbol\n",
    "    csv_file = ''.join([stock_symbol, '.csv'])    # Create the filename to read from the local directory \n",
    "    \n",
    "    # Read files found in the local directory\n",
    "    if os.path.isfile(csv_file):\n",
    "        print(index, csv_file)\n",
    "        add_to_data_matrix(csv_file, index)\n",
    "    else:\n",
    "        print(\"File not found!\")\n",
    "        \n",
    "print('Done creating prepared_data_matrix!')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load the SPY also known as SPYDR\n",
    "spydr_data = pd.read_csv('SPY.csv')\n",
    "y = spydr_data[['Open', 'High', 'Low', 'Close']].values"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(4482, 4)"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(4482, 505, 4)"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "prepared_data_matrix.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create 2d matrix from 3d.\n",
    "\n",
    "X = prepared_data_matrix.reshape(days * components, columns)\n",
    "#X = prepared_data_matrix"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "X.tofile('X.tsv', sep=\"\\t\", format=\"%s\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Plots\n",
    "import matplotlib as mpl\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.cm as cm\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "# Clustering\n",
    "from sklearn.manifold import TSNE\n",
    "from sklearn import cluster\n",
    "# Bokeh\n",
    "from bokeh.io import output_notebook\n",
    "from bokeh.plotting import figure, show, ColumnDataSource\n",
    "from bokeh.models import HoverTool"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%matplotlib inline\n",
    "output_notebook()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Normalize the data\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "X = StandardScaler().fit_transform(X)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#TSNE\n",
    "from sklearn.manifold import TSNE\n",
    "\n",
    "tsne_model = TSNE(n_components=2, verbose=1, random_state=0, angle=.99, init='pca')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_tsne = tsne_model.fit_transform(X)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "cl = cluster.AgglomerativeClustering(10)\n",
    "cl.fit(X_tsne)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(12,4))\n",
    "plt.subplot(1,2,1)\n",
    "cmap = plt.cm.get_cmap('jet')\n",
    "plt.scatter(X_tsne[:len(y),0], X_tsne[:len(y),1], \n",
    "            alpha=0.5, c=y, cmap=cmap, s=20)\n",
    "plt.colorbar()\n",
    "plt.subplot(1,2,2)\n",
    "plt.scatter(X_tsne[len(y):,0], X_tsne[len(y):,1], \n",
    "            alpha=0.4, c=cl.labels_[len(y):], marker='s', s=20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
